export interface JobType {
  accommodation_type_id: number;
  application_id: number | null;
  application_time: number | null;
  created_time: string;
  day_off: string;
  district: string | null;
  edit_allow: number;
  employer_nationality_id: number;
  employer_type_id: number;
  expire_date: string;
  family_member_count: string;
  family_type_id: number;
  helper_contract_status_id: number;
  helper_only_local_apply: number | null;
  helper_req_experience_max: number;
  helper_req_experience_min: number;
  helper_req_gender: string;
  helper_req_nationality_id: number | null;
  helper_req_religion_id: number | null;
  icon_thumbnail: string;
  job_description: string;
  job_id: number;
  job_location_id: number;
  job_position_id: number;
  job_post_url: string;
  job_type_id: number;
  location_city_id: number | null;
  location_state_id: number | null;
  meta_data: string;
  modified_time: string;
  page_title: string;
  pet_in_home: number;
  post_manager: string;
  publish_date: string;
  reference_no: string;
  required_skill: number[];
  salary_currency_type_id: number;
  salary_offer_max: number;
  salary_offer_min: number;
  salary_offer_type: string;
  salary_old_string: number | null;
  save_job: number;
  start_date: string;
  start_date_flexiblity: number;
  status: string;
  thread_id: number | null;
  title: string;
  very_active: number;
}
