import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Suspense } from "react";

const inter = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Helper Place",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-10/12 mx-auto`}>
        {/* <Suspense fallback={<div className="text-black">loadingg....</div>}> */}
        <Navbar />
        {/* </Suspense> */}
        {children}
      </body>
    </html>
  );
}
